Working with payloads
SantiagoParraDev-gmail-com/lookup pull request #18
Opened 2024-06-19 18:55 UTC by nicolasparrague

2024-06-21 21:22 UTC, SantiagoParraGuerrero commented
@nicolasparrague you are failing a job

2024-06-22 18:20 UTC, SantiagoParraGuerrero requested changes

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/classes/AccountContactLookup.cls
> +    public final static Map<String, Object> ACCOUNT_ICON = new Map<String, Object>{
Why is this called account icon?

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/classes/AccountLookup.cls
> +    String searchTerm,
Can you use a code format?  You keep making code formatting mistakes

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/classes/AccountLookup.cls
> +            System.debug(account);
Remove debug statements

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.html
> +              <p>{accountText}</p>
Do

Your account selected was {selectedAccount.Name}

Do the same for the contact

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    return this._accountText;
Why a get set for this?
Does not me make sense to me

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    return this._contactText;
Same here 
Why is this marked as api?

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    if (this.accountValue !== undefined) {
Do 
If !this.account
Instead

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    if (this.accountValue === undefined || this.contactValue !== undefined) {
Same here

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    return !this.accountValue;
Don't need this
Just use a lwc:if this.account on your html

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js-meta.xml
> +    <apiVersion>59.0</apiVersion>
Make sure you are using the latest api version checkout other files

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.html
> +<template>
Why is this file called lookup account it is just a lookup account it does more than than

Called it 

workingWithPayloads instead

2024-06-22 18:20 UTC, SantiagoParraGuerrero commented on src-lookup-sample/main/default/lwc/lookupAccount/__tests__/lookupAccount.test.js
> +        expect(element.accountText).toBe('Your account selected was Account name');
You can't make an api variable just for the purpose of exposing it to the test class that is not Right

2024-07-10 15:38 UTC, nicolasparrague commented on src-lookup-sample/main/default/lwc/lookupAccount/lookupAccount.js
> +    return !this.accountValue;
the requirement says that the contact must be deactivated when you do not select the account

2024-07-12 15:57 UTC, SantiagoParraGuerrero approved these changes

2024-07-12 15:57 UTC, merged